### ISSUE TITLE
As a PyCharm plugin?

### ISSUE THREAD

**Issue by tollis-hunt** [rpalo/pycharm-old-hope#1]
Just curious if this could be made to download as a plugin, like a lot of other PyCharm themes?

**Comment by rpalo** [comment]
I'm down to do that, I just have very little knowledge of the PyCharm/JetBrains plugin ecosystem or time to dive into it.  If you wanted to dig into it and submit a pull request, I'm open to it, though. 😃

**Comment by tollis-hunt** [comment]
cool! i may just do that eventually :) 

thanks for the response
